version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: plant_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: plantdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: plant_fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app # This maps your local folder to the container for hot-reloading!

  frontend:
    build: ./frontend
    container_name: plant_react_pwa
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    env_file:
      - ./frontend/.env
volumes:
  postgres_data:
