"""add treatment fields to disease_logs

Revision ID: 0057d26104b4
Revises: 003_add_botanical_data
Create Date: 2026-05-26 15:33:18.116223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0057d26104b4'
down_revision: Union[str, Sequence[str], None] = '003_add_botanical_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease_logs', sa.Column('treatment_duration_days', sa.Integer(), nullable=True))
    op.add_column('disease_logs', sa.Column('expected_resolve_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_disease_logs_image_hash'), 'disease_logs', ['image_hash'], unique=False)
    op.alter_column('plants', 'botanical_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'botanical_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_disease_logs_image_hash'), table_name='disease_logs')
    op.drop_column('disease_logs', 'expected_resolve_date')
    op.drop_column('disease_logs', 'treatment_duration_days')
    # ### end Alembic commands ###
