"""add_treatment_recommendation_to_disease_logs

Revision ID: 25d9a0a78021
Revises: 002
Create Date: 2026-05-14 14:58:13.248119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d9a0a78021'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease_logs', sa.Column('treatment_recommendation', sa.String(), nullable=True))
    op.alter_column('plants', 'is_toxic_to_pets',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'is_toxic_to_pets',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('disease_logs', 'treatment_recommendation')
    # ### end Alembic commands ###
