"""add feedback fields to disease_logs

Revision ID: dcb205e87446
Revises: 0057d26104b4
Create Date: 2026-05-26 15:35:46.359342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb205e87446'
down_revision: Union[str, Sequence[str], None] = '0057d26104b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease_logs', sa.Column('feedback_score', sa.Integer(), nullable=True))
    op.add_column('disease_logs', sa.Column('feedback_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disease_logs', 'feedback_note')
    op.drop_column('disease_logs', 'feedback_score')
    # ### end Alembic commands ###
