"""add_image_url_to_plants

Revision ID: e9d54da691bd
Revises: 25d9a0a78021
Create Date: 2026-05-17 14:03:54.324478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d54da691bd'
down_revision: Union[str, Sequence[str], None] = '25d9a0a78021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'image_url')
    # ### end Alembic commands ###
